### ISSUE TITLE
Some questions about mucko

### ISSUE THREAD

**Issue by rowrycho** [jlian2/Masked-Proxy-Loss-for-Text-Indepedent-Speaker-Verification#1]
Hello, because the mocko project does not have an issue, I am asking a question here.
Where can the data of mocko project be downloaded? Can you add the steps for downloading and processing data below? Thanks!

**Comment by jlian2** [comment]
Hi! Thanks for reaching! Actually I am not the author of Mucko paper and might not have the right to release these datasets. But I think you can try to reach the first-author of Mucko paper ?
